default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: landescape_development

test:
  <<: *default
  database: landescape_test

production:
  <<: *default
  database: landescape_production
  username: landescape
  password: <%= ENV['LANDESCAPE_DATABASE_PASSWORD'] %>
